Shop.Web/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.Web.Data;
using Shop.Web.Data.Repositories;
using Shop.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Web.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrderRepository orderRepository;
        private readonly IProductRepository productRepository;

        public OrdersController(IOrderRepository orderRepository, IProductRepository productsRepository)
        {
            this.orderRepository = orderRepository;
            this.productRepository = productsRepository;
        }


        public async Task<IActionResult> Index()
        {
            var model = await orderRepository.GetOrdersAsync(this.User.Identity.Name);
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            var model = await this.orderRepository.GetDetailTempsAsync(this.User.Identity.Name);
            return this.View(model);
        }

        //Agregar productos
        /// <summary>
        ///    Al adicionar un producto le pasamos
        ///    el addItenViewModel
        ///    se asume que la cantidad es uno
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        /// 
        public IActionResult AddProduct()
        {
            var model = new AddItemViewModel
            {
                Quantity = 1,
                //armamos la lista de producto
                //Este es el dromDopList
                Products = this.productRepository.GetComboProducts()
            };

            return View(model);
        }
        
        //Submit
        [HttpPost]
        public async Task<IActionResult> AddProduct(AddItemViewModel model)
        {
            //el modelo es válido?
            if (this.ModelState.IsValid)
            {
                //si es válido indica que es un valor positivo
                //agregamos al repositorio ese modelo, pero al usuario logueado
                await this.orderRepository.AddItemToOrderAsync(model, this.User.Identity.Name);
                return this.RedirectToAction("Create");
            }

            return this.View(model);
        }

        //metodo para el delete del OrderDetailTemp
        public async Task<IActionResult> DeleteItem(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }
            await this.orderRepository.DeleteDetailTempAsync(id.Value);
            return this.RedirectToAction("Create");
            
        }

        //metodo para incrementar la cantidad
        public async Task<IActionResult>Increase(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }

            await this.orderRepository.ModifyOrderDetailTempQuantityAsync(id.Value,1);
            return this.RedirectToAction("Create");
        }
        //metodo para decrementar la cantidad

        public async Task<IActionResult> Decrease(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await this.orderRepository.ModifyOrderDetailTempQuantityAsync(id.Value, -1);
            return this.RedirectToAction("Create");
        }

        public async Task<IActionResult> ConfirmOrder()
        {
            //confirmar la orden del usuario logueado
            var response = await this.orderRepository.ConfirmOrderAsync(this.User.Identity.Name);
            if (response)
            {
                //si lo hace mandalo al index
                return this.RedirectToAction("Index");
            }
            //mandalo a la vista create
            return this.RedirectToAction("Create");
        }

        //despachar la orden
        public async Task<IActionResult> Deliver(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await this.orderRepository.GetOrdersAsync(id.Value);
            if (order == null)
            {
                return NotFound();
            }

            var model = new DeliverViewModel
            {
                Id = order.Id,
                DeliveryDate = DateTime.Today
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Deliver(DeliverViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                await this.orderRepository.DeliverOrder(model);
                return this.RedirectToAction("Index");
            }

            return this.View();
        }



    }
}

Shop.Web/Controllers/ProductsController.cs
namespace Shop.Web.Controllers
{
    using Data;
    using Data.Entities;
    using Helpers;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Shop.Web.Models;
    using System;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;

    
    public class ProductsController : Controller
    {
        private readonly IProductRepository productRepository;

        private readonly IUserHelper UserHelper;

        public ProductsController(IProductRepository productRepository, IUserHelper userHelper)
        {
            this.productRepository = productRepository;
            this.UserHelper = userHelper;
        }

        // GET: Products
        public IActionResult Index()
        {
            return View(this.productRepository.GetAll().OrderBy(p => p.Name));
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            var product = await this.productRepository.GetByIdAsync(id.Value);
            if (product == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            return View(product);
        }
        [Authorize(Roles = "Admin")]
        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        public async Task<IActionResult> Create(ProductViewModel view)
        {
           
            if (ModelState.IsValid)
            {
                


                // #region RUTA_PARA_GUARDAR_IMG_EN EL SERVIDOR
                var path = string.Empty;
                //si el imageFile es diferente de null
                //y si .lengt(tamaño físico) es mayor a cero
                if (view.ImageFile != null && view.ImageFile.Length > 0)
                {
                    //guid hace que n repita es un viajao de numeros
                    var guid = Guid.NewGuid().ToString();
                    var file = $"{guid}.jpg";
                    path = Path.Combine(
                        Directory.GetCurrentDirectory(),
                        "wwwroot\\images\\Products",
                        file);


                    // SUBIR LA IMG AL SERVIDOR
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await view.ImageFile.CopyToAsync(stream);
                    }
                   // #endregion


                    path = $"~/images/Products/{file}";
                }

               
               
                view.User = await this.UserHelper.GetUserByEmailAsync(this.User.Identity.Name);
                //cambiar de productViewModel a Product
                var product = this.ToProduct(view, path);
                await this.productRepository.CreateAsync(product);
                return RedirectToAction(nameof(Index));
            }

            //si falla lo devolvemos a la vista1
            return View(view);
        }
        // En el post convertimos el productViewModel a  Product
        private Product ToProduct(ProductViewModel view, string path)
        {
            return new Product
            {
                Id = view.Id,
                ImageUrl = path,
                IsAvailabe = view.IsAvailabe,
                LastPurchase = view.LastPurchase,
                LastSale = view.LastSale,
                Name = view.Name,
                Price = view.Price,
                Stock = view.Stock,
                User = view.User

            };
        }

        [Authorize(Roles = "Admin")]
        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await this.productRepository.GetByIdAsync(id.Value);
            if (product == null)
            {
                return NotFound();
            }

            var view = this.ToProductViewModel(product);

            return View(view);
        }
        //le pasamos el producto que vamos a editar
        //por lo tanto convertimos el Product a productViewModel
        private ProductViewModel ToProductViewModel(Product product)
        {
            return new ProductViewModel
            {
                Id = product.Id,
                IsAvailabe = product.IsAvailabe,
                LastPurchase = product.LastPurchase,
                LastSale = product.LastSale,
                ImageUrl = product.ImageUrl,
                Name = product.Name,
                Price = product.Price,
                Stock = product.Stock,
                User = product.User
            };
        }



        // POST: Products/Edit/5
        //Aquí recibe un productViewModel
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductViewModel view)
        {
            if (ModelState.IsValid)
            {
                try
                {

               
                // #region RUTA_PARA_GUARDAR_IMG_EN EL SERVIDOR
                var path = view.ImageUrl;
                //si el imageFile es diferente de null
                //y si .lengt(tamaño físico) es mayor a cero
                if (view.ImageFile != null && view.ImageFile.Length > 0)
                {
                    //guid hace que n repita es un viajao de numeros
                    var guid = Guid.NewGuid().ToString();
                    var file = $"{guid}.jpg";
                    path = Path.Combine(
                        Directory.GetCurrentDirectory(),
                        "wwwroot\\images\\Products",
                        file);


                    // SUBIR LA IMG AL SERVIDOR
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await view.ImageFile.CopyToAsync(stream);
                    }
                    // #endregion


                    path = $"~/images/Products/{file}";
                }


      
               view.User = await this.UserHelper.GetUserByEmailAsync(this.User.Identity.Name);
                //cambiar de productViewModel a Product
                var product = this.ToProduct(view, path);
                await this.productRepository.UpdateAsync(product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if(!await this.productRepository.ExistAsync(view.Id))
                    {
                        return NotFound();
                    }
                    else
                    { throw;
                    }
                   
                }
                return RedirectToAction(nameof(Index));
            }

            return View(view);
        }

        [Authorize(Roles = "Admin")]
        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await this.productRepository.GetByIdAsync(id.Value);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await this.productRepository.GetByIdAsync(id);
            await this.productRepository.DeleteAsync(product);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ProductNotFound()
        {
            return this.View();
        }

        



    }
}

#region ASI ESTABA EL CÓDIGO ANTES DEL GENERICREPOSITORY EN EL CONTROLADOR
/* using System.Threading.Tasks;
using Data;
using Data.Entities;
using Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


public class ProductsController : Controller
{

private readonly IProductRepository productRepository;
private readonly IUserHelper userHelper;

#region MODIFICACIÓN DEL DATA CONTEXT

/// <summary>
/// Se ha dejado en pelotas el constructor, ya que hacía una inyección que 
/// lo vinculaba directaente a la BD
/// </summary>
/// <returns></returns>
// private readonly DataContext _context;

//Esta inyeccion viene desde el D:\Projects\Shop\Shop.Web\Startup.cs
//public ProductsController(DataContext context)
//{
//    _context = context;
//}
#endregion

public ProductsController(IProductRepository productRepository, IUserHelper userHelper)
{
   this.productRepository = productRepository;
   this.userHelper = userHelper;
}

// GET: Products
public IActionResult Index()
{
   return View(this.repository.GetProducts());
}

// GET: Products/Details/5
public IActionResult Details(int? id)
{
   if (id == null)
   {
       return NotFound();
   }

   var product = this.repository.GetProduct(id.Value);

   if (product == null)
   {
       return NotFound();
   }

   return View(product);
}

// GET: Products/Create
public IActionResult Create()
{
   return View();
}

// POST: Products/Create
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Create(Product product)
{
   if (ModelState.IsValid)
   {
       //TODO:CHANGE FOR THE LOGGED USER
       product.User = await this.userHelper.GetUserByEmailAsync("drogermoises@gmail.com");
       this.repository.AddProduct(product);
       await this.repository.SaveAllAsync();
       return RedirectToAction(nameof(Index));
   }
   return View(product);
}

// GET: Products/Edit/5
public IActionResult Edit(int? id)
{

   if (id == null)
   {
       return NotFound();
   }

Shop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shop.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Shop.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!--d-sm-inline-flex flex-sm-row-reverse-->
                <div class="navbar-collapse collapse ">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (!this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                        }


                        @if (this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a></li>
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a></li>
                            <li><a asp-area="" asp-controller="Account" asp-action="Index">Users</a></li>
                        }


                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (this.User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">
                                <a asp-area="" asp-controller="Account" asp-action="ChangeUser">@this.User.Identity.Name</a>
                            </li>


                            <li class="nav-item"><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>

                        }
                        else
                        {
                            <li class="nav-item"><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
        <script src="~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>

    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>